cloud:
  aws:
    credentials:
      access-key:
      secret-key:

aws:
  open-search:
    id: ${AWS_OPEN_SEARCH_ID}
    pwd: ${AWS_OPEN_SEARCH_PWD}
    region: ${AWS_OPEN_SEARCH_REGION}
    endpoint: ${AWS_OPEN_SEARCH_ENDPOINT}

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

