# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-alpine
LABEL authors="samsamohoh"

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file into the container at /app
COPY build/libs/*.jar app.jar

# Run the JAR file
ENTRYPOINT ["java", "-jar", "app.jar"]
