name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Remove Gradle caches
        run: rm -rf ~/.gradle/caches/
        shell: bash

      #      - name: Cache Gradle packages
      #        id: cache-gradle
      #        uses: actions/cache@v4
      #        with:
      #          path: |
      #            ~/.gradle/caches
      #            ~/.gradle/wrapper
      #          key: ${{ runner.os }}-gradle-${{ hashFiles('searchEngineProject/**/*.gradle*', 'searchEngineProject/**/gradle-wrapper.properties') }}
      #          restore-keys: |
      #            ${{ runner.os }}-gradle-
      #
      #      - name: Cache check
      #        if: steps.cache-gradle.outputs.cache-hit == 'true'
      #        run: echo 'Gradle cache hit!'

      - name: Grant execute permission for gradlew
        run: chmod +x ./searchEngineProject/gradlew
        working-directory: .

      - name: Create application.yml.template
        run: |
          mkdir -p searchEngineProject/src/main/resources
          cat > searchEngineProject/src/main/resources/application.yml.template <<EOL
          aws:
            open-search:
              id: \${{ secrets.AWS_OPEN_SEARCH_ID }}
              pwd: \${{ secrets.AWS_OPEN_SEARCH_PWD }}
              region: \${{ secrets.AWS_OPEN_SEARCH_REGION }}
              endpoint: \${{ secrets.AWS_OPEN_SEARCH_ENDPOINT }}
          spring:
            mvc:
              pathmatch:
                matching-strategy: ant_path_matcher
          
          server:
            servlet:
              encoding:
                charset: UTF-8
                enabled: true
                force: true
          EOL

      - name: Set Yaml
        run: |
          envsubst < searchEngineProject/src/main/resources/application.yml.template > searchEngineProject/src/main/resources/application.yml
          cat searchEngineProject/src/main/resources/application.yml
        env:
          AWS_OPEN_SEARCH_ID: ${{ secrets.AWS_OPEN_SEARCH_ID }}
          AWS_OPEN_SEARCH_PWD: ${{ secrets.AWS_OPEN_SEARCH_PWD }}
          AWS_OPEN_SEARCH_REGION: ${{ secrets.AWS_OPEN_SEARCH_REGION }}
          AWS_OPEN_SEARCH_ENDPOINT: ${{ secrets.AWS_OPEN_SEARCH_ENDPOINT }}

      - name: Build with Gradle
        run: ./gradlew clean build --stacktrace --warn
        working-directory: ./searchEngineProject

      - name: Run tests
        run: ./gradlew test --warn
        working-directory: ./searchEngineProject

      - name: Store test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: searchEngineProject/build/test-results

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: searchEngineProject/build/libs/*.jar