name: dockerhub-image-push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x searchEngineProject/gradlew

      - name: Create application.yml.template
        run: |
          mkdir -p searchEngineProject/src/main/resources
          cat > searchEngineProject/src/main/resources/application.yml.template <<EOL
          aws:
            open-search:
              id: \${{ secrets.AWS_OPEN_SEARCH_ID }}
              pwd: \${{ secrets.AWS_OPEN_SEARCH_PWD }}
              region: \${{ secrets.AWS_OPEN_SEARCH_REGION }}
              endpoint: \${{ secrets.AWS_OPEN_SEARCH_ENDPOINT }}
          spring:
            mvc:
              pathmatch:
                matching-strategy: ant_path_matcher
          
          server:
            servlet:
              encoding:
                charset: UTF-8
                enabled: true
                force: true
          EOL

      - name: Set Yaml
        run: |
          envsubst < searchEngineProject/src/main/resources/application.yml.template > searchEngineProject/src/main/resources/application.yml
          cat searchEngineProject/src/main/resources/application.yml
        env:
          AWS_OPEN_SEARCH_ID: ${{ secrets.AWS_OPEN_SEARCH_ID }}
          AWS_OPEN_SEARCH_PWD: ${{ secrets.AWS_OPEN_SEARCH_PWD }}
          AWS_OPEN_SEARCH_REGION: ${{ secrets.AWS_OPEN_SEARCH_REGION }}
          AWS_OPEN_SEARCH_ENDPOINT: ${{ secrets.AWS_OPEN_SEARCH_ENDPOINT }}

      - name: Build with Gradle
        run: ./gradlew clean build --stacktrace --warn
        working-directory: searchEngineProject

      - name: Run tests
        run: ./gradlew test --warn
        working-directory: searchEngineProject

      - name: Upload test report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: searchEngineProject/build/reports/tests/test

      - name: Store test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: searchEngineProject/build/test-results

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: searchEngineProject
          file: searchEngineProject/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/aws-open-search:latest