name: CD Workflow

on:
  workflow_run:
    workflows: ["CI Workflow"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    env:
      AWS_OPEN_SEARCH_ID: ${{ secrets.AWS_OPEN_SEARCH_ID }}
      AWS_OPEN_SEARCH_PWD: ${{ secrets.AWS_OPEN_SEARCH_PWD }}
      AWS_OPEN_SEARCH_REGION: ${{ secrets.AWS_OPEN_SEARCH_REGION }}
      AWS_OPEN_SEARCH_ENDPOINT: ${{ secrets.AWS_OPEN_SEARCH_ENDPOINT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug Info
        run: |
          echo "Workflow Run ID: ${{ github.event.workflow_run.id }}"
          echo "Workflow Run Status: ${{ github.event.workflow_run.conclusion }}"
          echo "Artifact Name: ci-workflow-application-jar"
          echo "Run ID: ${{ github.event.workflow_run.id }}"
          echo "Parent Run ID: ${{ github.event.workflow_run.parent_run_id }}"

      - name: Download JAR file
        uses: actions/download-artifact@v4
        with:
          name: ci-workflow-application-jar
          path: ./searchEngineProject/build/libs
          run-id: ${{ github.event.workflow_run.id }}

      - name: Verify Download
        run: |
          echo "Current working directory:"
          pwd
          echo "Contents of searchEngineProject/build/libs:"
          ls -l searchEngineProject/build/libs

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          working-directory: ./searchEngineProject

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        env:
          working-directory: ./searchEngineProject

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./searchEngineProject
          file: ./searchEngineProject/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/aws-open-search:latest
