name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./searchEngineProject

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Print working directory
        run: pwd

      - name: List project files
        run: ls -R

      - name: Cache Gradle packages
        id: cache-gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('searchEngineProject/**/*.gradle*', 'searchEngineProject/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
          fail-on-cache-miss: false

      - name: Print cache key
        run: echo ${{ runner.os }}-gradle-${{ hashFiles('searchEngineProject/**/*.gradle*', 'searchEngineProject/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Check
        if: steps.cache-gradle.outputs.cache-hit == 'true'
        run: echo 'Gradle cache hit!'

      - name: Check Cache Miss
        if: steps.cache-gradle.outputs.cache-hit != 'true'
        run: |
          echo 'Cache miss! Gradle cache not found.'
          echo "Cache key: ${{ runner.os }}-gradle-${{ hashFiles('searchEngineProject/**/*.gradle*', 'searchEngineProject/gradle/wrapper/gradle-wrapper.properties') }}"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build --info --build-cache

      - name: Run tests
        run: ./gradlew test --info

      - name: Store test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: searchEngineProject/build/test-results

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: searchEngineProject/build/libs/*.jar

      - name: Save Gradle cache
        if: always()
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('searchEngineProject/**/*.gradle*', 'searchEngineProject/gradle/wrapper/gradle-wrapper.properties') }}
