name: CD Workflow

on:
  workflow_run:
    workflows: ["CI Workflow"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_OPEN_SEARCH_ID: "${{ secrets.AWS_OPEN_SEARCH_ID }}"
      AWS_OPEN_SEARCH_PWD: "${{ secrets.AWS_OPEN_SEARCH_PWD }}"
      AWS_OPEN_SEARCH_REGION: "${{ secrets.AWS_OPEN_SEARCH_REGION }}"
      AWS_OPEN_SEARCH_ENDPOINT: "${{ secrets.AWS_OPEN_SEARCH_ENDPOINT }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download JAR file
        uses: actions/download-artifact@v4
        with:
          name: application-jar
          path: build/libs

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/aws-open-search:latest